import React, { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Action, Avatar, HQ, Notice, PEOPLE, Screen, Tap } from './HomeQuestUI';

const TABLE=require('./table.png');
type CareState='open'|'offered'|'handoff'|'done';
interface CareTask{id:number;title:string;area:string;done:boolean}
export interface CleanlinessScreenProps{onBack:()=>void}
const MOCK_TASKS:CareTask[]=[{id:1,title:'Clear shared table',area:'Living room',done:false},{id:2,title:'Fold clean laundry',area:'Laundry',done:false},{id:3,title:'Return loose items',area:'Hallway',done:true}];
const AI_SPLIT=['Gather items by room','Wipe the shared table','Fold towels together','Put supplies away'];

export default function CleanlinessScreen({onBack}:CleanlinessScreenProps){
 const [state,setState]=useState<CareState>('open'),[tasks,setTasks]=useState(MOCK_TASKS),[suggested,setSuggested]=useState(AI_SPLIT.map((title,id)=>({id,title}))),[expanded,setExpanded]=useState(false),[approved,setApproved]=useState(false),[noorAgreed,setNoorAgreed]=useState(false),[aliAgreed,setAliAgreed]=useState(false),[message,setMessage]=useState<string|null>(null);
 const flash=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(null),1600)};
 const offer=()=>{setState('offered');flash('Your offer was shared')};
 const pass=()=>{setState('handoff');setNoorAgreed(true);flash('Waiting for Ali to agree')};
 const agreeAli=()=>{setAliAgreed(true);flash('Handoff agreed together')};
 const done=(id:number)=>{setTasks(old=>old.map(x=>x.id===id?{...x,done:true}:x));flash('Marked done for the shared home')};
 return <Screen title="Shared home care" kicker="RESET TOGETHER" color={HQ.peach} art={TABLE} onBack={onBack}>
  <View style={s.hero}><View style={s.heroCopy}><Text style={s.heroLabel}>TODAY’S GENTLE RESET</Text><Text style={s.heroTitle}>Living room together</Text><Text style={s.heroSub}>Three small areas · about 20 minutes</Text></View><Image source={TABLE} style={s.table} resizeMode="contain"/></View>
  <Text style={s.mantra}>We take care of our shared home together.</Text>{message&&<Notice text={message}/>}<View style={s.people}><Avatar source={PEOPLE.ali} name="Ali" badge="⌁ Fixer" highlight={state!=='open'}/><Avatar source={PEOPLE.noor} name="Noor" badge="Laundry Pro" highlight={state==='handoff'}/></View>
  <View style={s.actions}><Action text={state==='open'?'I can help':'Helping ✓'} onPress={offer}/><Action text="Pass together" secondary onPress={pass}/></View>
  {state==='handoff'&&<View style={s.handoff}><Text style={s.handoffTitle}>Shared handoff</Text><Text style={s.handoffText}>Both people confirm before the task moves.</Text><View style={s.agreements}><View style={[s.agree,noorAgreed&&s.agreeDone]}><Text style={s.agreeText}>Noor ✓</Text></View><Tap onPress={agreeAli} style={[s.agree,aliAgreed&&s.agreeDone]}><Text style={s.agreeText}>{aliAgreed?'Ali ✓':'Ali · agree'}</Text></Tap></View>{noorAgreed&&aliAgreed&&<Action text="Complete handoff" onPress={()=>{setState('offered');flash('Task passed together')}}/>}</View>}
  <View style={s.sectionHead}><Text style={s.sectionTitle}>Areas asking for care</Text><Text style={s.small}>{tasks.filter(x=>!x.done).length} open</Text></View><View style={s.tasks}>{tasks.map(x=><View key={x.id} style={[s.task,x.done&&s.taskDone]}><View style={s.areaMark}><Text style={s.areaMarkText}>{x.area.charAt(0)}</Text></View><View style={{flex:1}}><Text style={[s.taskTitle,x.done&&s.doneText]}>{x.title}</Text><Text style={s.area}>{x.area}</Text></View>{x.done?<Text style={s.complete}>Done</Text>:<Action text="Done" secondary onPress={()=>done(x.id)}/>}</View>)}</View>
  <View style={s.ai}><Pressable onPress={()=>setExpanded(x=>!x)} style={s.aiHead}><View><Text style={s.aiLabel}>✦ AI SUGGESTION · FAMILY APPROVES</Text><Text style={s.aiTitle}>A fair, flexible split</Text></View><Text style={s.plus}>{expanded?'−':'+'}</Text></Pressable>{expanded&&<View>{suggested.map((x,i)=><View key={x.id} style={s.suggestRow}><Text style={s.number}>{i+1}</Text><TextInput value={x.title} onChangeText={title=>setSuggested(old=>old.map(y=>y.id===x.id?{...y,title}:y))} style={s.suggestInput}/><Pressable onPress={()=>setSuggested(old=>old.filter(y=>y.id!==x.id))}><Text style={s.remove}>×</Text></Pressable></View>)}{approved?<Notice text="Split accepted into the shared reset"/>:<View style={s.actions}><Action text="Suggest again" secondary onPress={()=>{setSuggested([...AI_SPLIT].reverse().map((title,id)=>({id:id+10,title})));flash('New split suggested')}}/><Action text="Suggest split" onPress={()=>setApproved(true)} disabled={!suggested.length}/></View>}</View>}</View>
  {tasks.every(x=>x.done)&&state!=='done'&&<Action text="Finish reset together" onPress={()=>{setState('done');flash('Shared reset complete')}}/>}{state==='done'&&<Notice text="Shared home reset complete" tone={HQ.mint}/>} 
 </Screen>;
}
const s=StyleSheet.create({hero:{height:137,borderRadius:22,backgroundColor:'#F2D2AD',padding:15,flexDirection:'row',overflow:'hidden'},heroCopy:{flex:1,justifyContent:'center'},heroLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:HQ.brand},heroTitle:{fontSize:21,fontWeight:'800',color:HQ.ink,marginTop:5},heroSub:{fontSize:10.5,color:HQ.muted,marginTop:6},table:{width:128,height:120},mantra:{fontSize:13,fontWeight:'700',fontStyle:'italic',color:HQ.brand,textAlign:'center',marginVertical:13},people:{flexDirection:'row',justifyContent:'center',gap:30,marginVertical:10},actions:{flexDirection:'row',gap:8,justifyContent:'flex-end',marginVertical:10},handoff:{borderRadius:18,padding:14,backgroundColor:HQ.lavender,marginVertical:10},handoffTitle:{fontSize:15,fontWeight:'800',color:HQ.ink},handoffText:{fontSize:10.5,color:HQ.muted,marginTop:3},agreements:{flexDirection:'row',gap:8,marginTop:10},agree:{flex:1,height:37,borderRadius:11,backgroundColor:HQ.white,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:HQ.line},agreeDone:{backgroundColor:HQ.mint},agreeText:{fontSize:10.5,fontWeight:'800',color:HQ.ink},sectionHead:{marginTop:15,flexDirection:'row',justifyContent:'space-between'},sectionTitle:{fontSize:18,fontWeight:'800',color:HQ.ink},small:{fontSize:10,color:HQ.muted},tasks:{gap:8,marginTop:10},task:{minHeight:67,borderRadius:17,padding:10,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,flexDirection:'row',alignItems:'center',gap:10},taskDone:{opacity:.62,backgroundColor:'#E4E7E1'},areaMark:{width:35,height:35,borderRadius:12,backgroundColor:HQ.peach,alignItems:'center',justifyContent:'center'},areaMarkText:{fontSize:12,fontWeight:'900',color:HQ.ink},taskTitle:{fontSize:12.5,fontWeight:'800',color:HQ.ink},doneText:{textDecorationLine:'line-through'},area:{fontSize:9.5,color:HQ.muted,marginTop:3},complete:{fontSize:10,fontWeight:'900',color:HQ.success},ai:{borderRadius:20,padding:14,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,marginVertical:17},aiHead:{height:58,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},aiLabel:{fontSize:8.5,fontWeight:'900',letterSpacing:1,color:'#79538B'},aiTitle:{fontSize:15,fontWeight:'800',color:HQ.ink,marginTop:4},plus:{fontSize:24,color:HQ.ink},suggestRow:{minHeight:41,flexDirection:'row',alignItems:'center',borderTopWidth:1,borderTopColor:HQ.line},number:{width:22,fontSize:9,fontWeight:'900',color:HQ.brand},suggestInput:{flex:1,color:HQ.ink,fontSize:12},remove:{fontSize:20,color:HQ.muted}});
