import React, { useRef, useState } from 'react';
import { Animated, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Action, Avatar, HQ, Notice, PEOPLE, Screen, Tap } from './HomeQuestUI';

const FRIDGE=require('./fridge_open.png');
type FoodState='loading'|'empty'|'ready';
interface GroceryItem{id:number;name:string;by:string}
interface Prep{id:number;title:string}
export interface FoodScreenProps{onBack:()=>void}
const MOCK_GROCERIES:GroceryItem[]=[{id:1,name:'Milk',by:'Noor'},{id:2,name:'Fresh mint',by:'Ali'}];
const AI_PREP=['Check ingredients','Buy missing items','Prepare salad','Set the table'];

export default function FoodScreen({onBack}:FoodScreenProps){
 const [view,setView]=useState<FoodState>('ready'),[groceries,setGroceries]=useState(MOCK_GROCERIES),[draft,setDraft]=useState(''),[cooking,setCooking]=useState(false),[meal,setMeal]=useState('Lemon chicken & rice'),[expanded,setExpanded]=useState(false),[prep,setPrep]=useState<Prep[]>(AI_PREP.map((title,id)=>({id,title}))),[approved,setApproved]=useState(false),[message,setMessage]=useState<string|null>(null); const stack=useRef(new Animated.Value(0)).current;
 const flash=(text:string)=>{setMessage(text);setTimeout(()=>setMessage(null),1600)};
 const add=()=>{const name=draft.trim();if(!name)return;setGroceries(x=>[...x,{id:Date.now(),name,by:'Noor'}]);setDraft('');setView('ready');flash('Added to the family list')};
 const toggle=()=>{setExpanded(x=>!x);Animated.spring(stack,{toValue:expanded?0:1,useNativeDriver:false,speed:16}).start()};
 const suggest=()=>{setMeal(meal.startsWith('Lemon')?'Vegetable machboos & salad':'Lemon chicken & rice');setApproved(false);flash('New meal suggested')};
 return <Screen title="Family food" kicker="SHARED KITCHEN" color={HQ.mint} art={FRIDGE} onBack={onBack}>
  <View style={s.hero}><Image source={FRIDGE} style={s.fridge} resizeMode="contain"/><View style={s.heroCopy}><Text style={s.label}>TONIGHT · 7:15 PM</Text><Text style={s.dinner}>{meal}</Text><Text style={s.sub}>Ayesha is cooking · Noor can prep</Text></View></View>
  <View style={s.people}><Avatar source={PEOPLE.ayesha} name="Ayesha" badge="✦ Great Cook" highlight/><Avatar source={PEOPLE.noor} name="Noor" badge="◇ Planner"/></View>
  <View style={s.actions}><Action text={cooking?'Cooking together ✓':'I can cook'} onPress={()=>{setCooking(true);flash('Ayesha received your offer')}}/><Action text="Suggest meal" secondary onPress={suggest}/></View>
  {message&&<Notice text={message}/>}<View style={s.sectionHead}><Text style={s.sectionTitle}>Running low</Text><Pressable onPress={()=>setView(view==='ready'?'empty':'ready')}><Text style={s.viewLink}>{view==='ready'?'Hide':'Show list'}</Text></Pressable></View>
  {view==='loading'?<Text style={s.loading}>Opening the fridge…</Text>:view==='empty'?<Notice text="The list is clear. Add anything the family needs." tone={HQ.yellow}/>:<View style={s.groceryRail}>{groceries.map(x=><Tap key={x.id} onPress={()=>{setGroceries(old=>old.filter(y=>y.id!==x.id));flash(`${x.name} checked off`)}} style={s.grocery}><Text style={s.groceryName}>{x.name}</Text><Text style={s.groceryBy}>{x.by} · tap when picked up</Text></Tap>)}</View>}
  <View style={s.addRow}><TextInput value={draft} onChangeText={setDraft} onFocus={()=>setView('ready')} placeholder="Add grocery item" placeholderTextColor={HQ.muted} style={s.input}/><Action text="Add item" onPress={add} disabled={!draft.trim()}/></View>
  <View style={s.aiWrap}>{!expanded&&<><View style={[s.slip,{top:9,backgroundColor:HQ.peach}]}/><View style={[s.slip,{top:4,backgroundColor:HQ.lavender}]}/></>}<Animated.View style={[s.ai,{maxHeight:stack.interpolate({inputRange:[0,1],outputRange:[100,380]})}]}><Pressable onPress={toggle}><View style={s.aiHead}><View style={s.spark}><Text>✦</Text></View><View style={{flex:1}}><Text style={s.aiLabel}>AI PREP SUGGESTION</Text><Text style={s.aiTitle}>Split dinner preparation</Text></View><Text style={s.plus}>{expanded?'−':'+'}</Text></View></Pressable>{expanded&&<View>{prep.map((x,i)=><View key={x.id} style={s.prepRow}><Text style={s.number}>{i+1}</Text><TextInput value={x.title} onChangeText={title=>setPrep(old=>old.map(y=>y.id===x.id?{...y,title}:y))} style={s.prepInput}/><Pressable onPress={()=>setPrep(old=>old.filter(y=>y.id!==x.id))}><Text style={s.remove}>×</Text></Pressable></View>)}{approved?<Notice text="Preparation added to the family plan"/>:<View style={s.actions}><Action text="Suggest again" secondary onPress={()=>{setPrep([...AI_PREP].reverse().map((title,id)=>({id:id+20,title})));flash('Suggestion refreshed')}}/><Action text="Split preparation" onPress={()=>setApproved(true)} disabled={!prep.length}/></View>}</View>}</Animated.View></View>
 </Screen>;
}
const s=StyleSheet.create({hero:{height:145,borderRadius:22,backgroundColor:'#DDE6D9',overflow:'hidden',flexDirection:'row',alignItems:'center',padding:14},fridge:{width:105,height:135},heroCopy:{flex:1},label:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:HQ.brand},dinner:{fontSize:21,lineHeight:25,fontWeight:'800',color:HQ.ink,marginTop:5},sub:{fontSize:10.5,color:HQ.muted,marginTop:7},people:{flexDirection:'row',justifyContent:'center',gap:28,marginVertical:14},actions:{flexDirection:'row',gap:8,justifyContent:'flex-end',marginVertical:10},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:16},sectionTitle:{fontSize:18,fontWeight:'800',color:HQ.ink},viewLink:{fontSize:10.5,fontWeight:'800',color:HQ.brand},loading:{padding:20,textAlign:'center',color:HQ.muted},groceryRail:{gap:7,marginTop:10},grocery:{padding:12,borderRadius:14,backgroundColor:HQ.yellow,flexDirection:'row',justifyContent:'space-between'},groceryName:{fontSize:12.5,fontWeight:'800',color:HQ.ink},groceryBy:{fontSize:9,color:HQ.muted},addRow:{flexDirection:'row',gap:8,marginTop:10},input:{flex:1,height:45,borderRadius:14,paddingHorizontal:13,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,color:HQ.ink},aiWrap:{marginTop:20,paddingBottom:10},slip:{position:'absolute',left:8,right:8,height:94,borderRadius:19,borderWidth:1,borderColor:HQ.line},ai:{minHeight:100,overflow:'hidden',borderRadius:20,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,padding:14},aiHead:{height:70,flexDirection:'row',alignItems:'center',gap:10},spark:{width:38,height:38,borderRadius:12,backgroundColor:HQ.lavender,alignItems:'center',justifyContent:'center'},aiLabel:{fontSize:8.5,fontWeight:'900',letterSpacing:1,color:'#79538B'},aiTitle:{fontSize:15,fontWeight:'800',color:HQ.ink,marginTop:3},plus:{fontSize:24,color:HQ.ink},prepRow:{minHeight:40,flexDirection:'row',alignItems:'center',borderTopWidth:1,borderTopColor:HQ.line},number:{width:22,fontSize:10,fontWeight:'900',color:HQ.brand},prepInput:{flex:1,color:HQ.ink,fontSize:12},remove:{fontSize:20,color:HQ.muted}});
