import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Dimensions, Image, ImageBackground, KeyboardAvoidingView, Modal, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ImageSourcePropType, StyleProp, ViewStyle } from 'react-native';
import { breakDownChore } from '../services/gemini';
import type { QuestPlan } from '../types';

// Keep this screen beside these supplied images: Metro requires literal paths.
const ASSETS = {
  mom: require('./mom.png'), dad: require('./dad.png'), ali: require('./Ali.png'), ayesha: require('./Ayesha.png'),
  room: require('./room_background.jpg'), fridge: require('./fridge.png'), fridgeOpen: require('./fridge_open.png'),
  door: require('./door.png'), picture: require('./picture.png'), table: require('./table.png'),
} as const;

const C = { ink:'#152820', paper:'#F4F1E8', white:'#FFFFFF', brand:'#0F5F5A', mint:'#B9E7D0', blue:'#B9D9F3', lavender:'#E0CEF2', peach:'#FFD9A8', yellow:'#F3DF82', orange:'#FF6B47', muted:'#60716A', line:'rgba(21,40,32,.15)', scrim:'rgba(16,35,30,.56)' };
type CategoryKey = 'food' | 'transport' | 'planning' | 'cleanliness';
type LocationKey = 'home' | 'moving' | 'school' | 'work';
type SheetMode = 'ask' | 'offer' | null;
export type ConnectionState = 'empty' | 'requestSent' | 'offerReceived' | 'connected';
export interface HomeScreenProps {
  userName?: string;
  familyName?: string;
  onNavigateToFood?: () => void;
  onNavigateToTransport?: () => void;
  onNavigateToPlanning?: () => void;
  onNavigateToCleanliness?: () => void;
  onNavigateToPlans?: () => void;
  onPlanGenerated?: (chore:string,plan:QuestPlan) => void;
  onOpenTasks?: () => void;
  onOpenProfile?: () => void;
}
interface Member { id:string; name:string; image:ImageSourcePropType; location:LocationKey; skill:string; mark:string }
interface Category { key:CategoryKey; label:string; color:string; image:ImageSourcePropType; mark:string; request:string; dx:number; dy:number }

const LOC:Record<LocationKey,{label:string;color:string}> = {
  home:{label:'Home',color:'#35A36F'}, moving:{label:'On the move',color:'#D59825'}, school:{label:'School',color:'#865BA0'}, work:{label:'Work',color:'#397CB0'},
};
const ME:Member = { id:'noor',name:'Noor',image:ASSETS.mom,location:'home',skill:'Planner',mark:'◇' };
const FAMILY:Member[] = [
  {id:'omar',name:'Omar',image:ASSETS.dad,location:'moving',skill:'Driver',mark:'→'},
  {id:'ali',name:'Ali',image:ASSETS.ali,location:'home',skill:'Navigator',mark:'⌁'},
  {id:'ayesha',name:'Ayesha',image:ASSETS.ayesha,location:'school',skill:'Great Cook',mark:'✦'},
];
const CATEGORIES:Category[] = [
  {key:'food',label:'Food',color:C.mint,image:ASSETS.fridge,mark:'F',request:'Prepare family dinner',dx:-8,dy:-174},
  {key:'transport',label:'Transport',color:C.blue,image:ASSETS.door,mark:'T',request:'Pickup at 5:00 PM',dx:-92,dy:-143},
  {key:'planning',label:'Planning',color:C.lavender,image:ASSETS.picture,mark:'P',request:'Plan our Friday outing',dx:-143,dy:-79},
  {key:'cleanliness',label:'Cleanliness',color:C.peach,image:ASSETS.table,mark:'C',request:'Reset the family room',dx:-151,dy:-8},
];
const NEEDS = [
  {id:'milk',category:'food' as CategoryKey,title:'Milk is running low',detail:'Before dinner'},
  {id:'dinner',category:'food' as CategoryKey,title:'Dinner needs preparation',detail:'Tonight'},
  {id:'pickup',category:'transport' as CategoryKey,title:'Pickup requested',detail:'5:00 PM'},
];
const category = (key:CategoryKey) => CATEGORIES.find(x => x.key === key) ?? CATEGORIES[0];

interface ScaleProps { children:React.ReactNode; onPress:()=>void; style?:StyleProp<ViewStyle>; disabled?:boolean; label?:string }
function ScalePress({children,onPress,style,disabled,label}:ScaleProps) {
  const scale=useRef(new Animated.Value(1)).current;
  const go=(toValue:number)=>Animated.spring(scale,{toValue,useNativeDriver:true,speed:36,bounciness:3}).start();
  return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} onPressIn={()=>go(.96)} onPressOut={()=>go(1)} style={disabled&&styles.disabled}><Animated.View style={[style,{transform:[{scale}]}]}>{children}</Animated.View></Pressable>;
}

function Avatar({member,size=48,highlighted=false,badge=true}:{member:Member;size?:number;highlighted?:boolean;badge?:boolean}) {
  const loc=LOC[member.location];
  return <View style={{width:size+8,alignItems:'center'}}>
    <View style={[styles.avatarRing,{width:size,height:size,borderRadius:size/2,borderColor:loc.color},highlighted&&styles.highlight]}><Image source={member.image} style={{width:size-8,height:size-8,borderRadius:(size-8)/2}} resizeMode="cover" /></View>
    <View style={[styles.liveDot,{backgroundColor:loc.color}]} />
    {badge&&<View style={styles.skillBadge}><Text style={styles.skillMark}>{member.mark}</Text><Text style={styles.skillText} numberOfLines={1}>{member.skill}</Text></View>}
  </View>;
}

function HomeObject({label,image,onPress,style,tint,children}:{label:string;image:ImageSourcePropType;onPress:()=>void;style:StyleProp<ViewStyle>;tint:string;children?:React.ReactNode}) {
  const lift=useRef(new Animated.Value(0)).current;
  const go=(v:number)=>Animated.spring(lift,{toValue:v,useNativeDriver:true,speed:34}).start();
  return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${label}`} onPress={onPress} onPressIn={()=>go(1)} onPressOut={()=>go(0)} style={[styles.homeObject,style]}>
    <Animated.View style={[styles.objectFill,{transform:[{translateY:lift.interpolate({inputRange:[0,1],outputRange:[0,-5]})},{scale:lift.interpolate({inputRange:[0,1],outputRange:[1,1.035]})}]}]}>{children??<Image source={image} style={styles.objectImage} resizeMode="contain"/>}</Animated.View>
    <View style={[styles.objectLabel,{backgroundColor:tint}]}><Text style={styles.objectLabelText}>{label}</Text></View>
  </Pressable>;
}

function CategoryPill({item,selected,onPress}:{item:Category;selected:boolean;onPress:()=>void}) {
  return <ScalePress onPress={onPress} style={[styles.categoryPill,{backgroundColor:selected?item.color:C.white,borderColor:selected?C.ink:C.line}]}><Image source={item.image} style={styles.categoryPillImage} resizeMode="contain"/><Text style={styles.categoryPillText}>{item.label}</Text></ScalePress>;
}

function SectionScreen({item,onBack}:{item:Category;onBack:()=>void}) {
  return <SafeAreaView style={[styles.sectionScreen,{backgroundColor:item.color}]}>
    <View style={styles.sectionHeader}><ScalePress onPress={onBack} label="Back to home" style={styles.backButton}><Text style={styles.backGlyph}>‹</Text></ScalePress><View><Text style={styles.eyebrow}>THE NOOR FAMILY</Text><Text style={styles.sectionTitle}>{item.label}</Text></View></View>
    <View style={styles.sectionArtWrap}><View style={styles.sectionHalo}/><Image source={item.image} style={styles.sectionArt} resizeMode="contain"/></View>
    <View style={styles.sectionContent}><View style={styles.readyRow}><View style={styles.readyDot}/><Text style={styles.readyText}>Ready to connect</Text></View><Text style={styles.sectionPrompt}>Family {item.label.toLowerCase()}, in one shared place.</Text><View style={styles.backendSlot}><Text style={styles.backendLabel}>FAMILY SPACE</Text><Text style={styles.backendTitle}>Your next {item.label.toLowerCase()} activity will appear here</Text></View></View>
  </SafeAreaView>;
}

interface SheetProps { visible:boolean; mode:Exclude<SheetMode,null>; onClose:()=>void; onAsk:(c:CategoryKey,r:string,t:string,to:string)=>void; onOffer:()=>void }
function AskOfferSheet({visible,mode,onClose,onAsk,onOffer}:SheetProps) {
  const [cat,setCat]=useState<CategoryKey>('transport'); const [request,setRequest]=useState(category('transport').request);
  const [time,setTime]=useState('5:00 PM'); const [recipient,setRecipient]=useState('Everyone'); const [sent,setSent]=useState(false);
  const slide=useRef(new Animated.Value(500)).current;
  useEffect(()=>{if(visible){setSent(false);Animated.spring(slide,{toValue:0,useNativeDriver:true,speed:18,bounciness:4}).start()}else slide.setValue(500)},[visible,slide]);
  const pick=(key:CategoryKey)=>{setCat(key);setRequest(category(key).request)};
  const submit=()=>{setSent(true);setTimeout(()=>mode==='ask'?onAsk(cat,request.trim()||category(cat).request,time,recipient):onOffer(),650)};
  return <Modal transparent visible={visible} animationType="fade" onRequestClose={onClose} statusBarTranslucent><KeyboardAvoidingView style={styles.modalRoot} behavior={Platform.OS==='ios'?'padding':undefined}><Pressable style={styles.modalScrim} onPress={onClose}/><Animated.View style={[styles.sheet,{transform:[{translateY:slide}]}]}><View style={styles.sheetHandle}/>
    {sent?<View style={styles.sentState}><View style={styles.sentMark}><Text style={styles.sentMarkText}>✓</Text></View><Text style={styles.sentTitle}>{mode==='ask'?'Request sent':'Offer sent'}</Text><Text style={styles.sentSub}>{mode==='ask'?'Your family can respond when they are ready.':'Omar knows you can help.'}</Text></View>:
    mode==='ask'?<ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"><Text style={styles.sheetKicker}>ASK</Text><Text style={styles.sheetTitle}>What would help?</Text><Text style={styles.fieldLabel}>SPACE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.categoryRow}>{CATEGORIES.map(x=><CategoryPill key={x.key} item={x} selected={cat===x.key} onPress={()=>pick(x.key)}/>)}</ScrollView><Text style={styles.fieldLabel}>REQUEST</Text><TextInput value={request} onChangeText={setRequest} style={styles.input} placeholder="What do you need?" placeholderTextColor={C.muted}/><Text style={styles.fieldLabel}>WHEN</Text><Choice values={['Now','5:00 PM','Tonight']} selected={time} onSelect={setTime}/><Text style={styles.fieldLabel}>WHO</Text><Choice values={['Everyone','Omar','Ayesha']} selected={recipient} onSelect={setRecipient}/><ScalePress onPress={submit} style={styles.primaryButton}><Text style={styles.primaryText}>Send request</Text></ScalePress></ScrollView>:
    <View><Text style={styles.sheetKicker}>OFFER</Text><Text style={styles.sheetTitle}>Where can you help?</Text><View style={styles.requestTicket}><View style={styles.ticketStripe}/><View style={styles.requestCopy}><Text style={styles.requestFrom}>OMAR · TRANSPORT</Text><Text style={styles.requestTitle}>Pickup from training</Text><Text style={styles.requestTime}>Today · 4:15 PM</Text></View><Avatar member={FAMILY[0]} size={54} highlighted/></View><View style={styles.matchNote}><Text style={styles.matchMark}>◇</Text><Text style={styles.matchText}><Text style={styles.matchStrong}>Good match:</Text> your Planner badge can help coordinate this pickup.</Text></View><ScalePress onPress={submit} style={styles.primaryButton}><Text style={styles.primaryText}>I can help</Text></ScalePress></View>}
  </Animated.View></KeyboardAvoidingView></Modal>;
}
function Choice({values,selected,onSelect}:{values:string[];selected:string;onSelect:(v:string)=>void}) { return <View style={styles.choiceRow}>{values.map(v=><ScalePress key={v} onPress={()=>onSelect(v)} style={[styles.choice,selected===v&&styles.choiceSelected]}><Text style={[styles.choiceText,selected===v&&styles.choiceTextSelected]}>{v}</Text></ScalePress>)}</View> }

function ConnectionPanel({state,title,time,onMeet,onView}:{state:ConnectionState;title:string;time:string;onMeet:()=>void;onView:()=>void}) {
  const meet=useRef(new Animated.Value(0)).current; const glow=useRef(new Animated.Value(0)).current;
  useEffect(()=>{if(state==='connected')Animated.parallel([Animated.spring(meet,{toValue:1,useNativeDriver:true,speed:13,bounciness:4}),Animated.timing(glow,{toValue:1,duration:520,useNativeDriver:false})]).start()},[state,meet,glow]);
  if(state==='empty')return null;
  if(state==='requestSent')return <View style={styles.waiting}><View style={styles.waitDot}/><Text style={styles.waitText}>Request sent · waiting for a family offer</Text></View>;
  const connected=state==='connected';
  return <View style={styles.connection}><View style={styles.connectionHead}><View><Text style={styles.connectionKicker}>{connected?'HANDLED TOGETHER':'AN OFFER ARRIVED'}</Text><Text style={styles.connectionTitle}>{title}</Text></View><Text style={styles.connectionTime}>{time}</Text></View><View style={styles.trackRow}><Animated.View style={{transform:[{translateX:meet.interpolate({inputRange:[0,1],outputRange:[0,57]})}]}}><Avatar member={ME} size={48} badge={false}/></Animated.View><View style={styles.track}><Animated.View style={[styles.trackFill,{width:glow.interpolate({inputRange:[0,1],outputRange:['0%','100%']})}]}/><View style={[styles.centre,connected&&styles.centreDone]}><Text style={styles.centreText}>{connected?'♥':'↔'}</Text></View></View><Animated.View style={{transform:[{translateX:meet.interpolate({inputRange:[0,1],outputRange:[0,-57]})}]}}><Avatar member={FAMILY[0]} size={48} badge={false}/></Animated.View></View><View style={styles.connectionNames}><Text style={styles.tiny}>Noor</Text><Text style={styles.tiny}>Omar</Text></View><ScalePress onPress={connected?onView:onMeet} style={[styles.meetButton,connected&&{backgroundColor:C.orange}]}><Text style={styles.meetText}>{connected?'View pickup':'Meet halfway'}</Text></ScalePress></View>;
}

function AiStack({onPlanGenerated}:{onPlanGenerated:(chore:string,plan:QuestPlan)=>void}) {
  const [expanded,setExpanded]=useState(false),[chore,setChore]=useState('Prepare family dinner'),[plan,setPlan]=useState<QuestPlan|null>(null),[generating,setGenerating]=useState(false),[error,setError]=useState(''); const anim=useRef(new Animated.Value(0)).current;
  const toggle=()=>{const next=!expanded;setExpanded(next);Animated.spring(anim,{toValue:next?1:0,useNativeDriver:false,speed:16,bounciness:4}).start()};
  const generate=async()=>{if(chore.trim().length<3){setError('Describe the task in a little more detail.');return}setError('');setGenerating(true);try{setPlan(await breakDownChore(chore))}catch(e){setError(e instanceof Error?e.message:'Could not generate subtasks.')}finally{setGenerating(false)}};
  const updateTitle=(id:number,title:string)=>setPlan(current=>current?{...current,tasks:current.tasks.map(task=>task.id===id?{...task,title}:task)}:current);
  const remove=(id:number)=>setPlan(current=>current?{...current,tasks:current.tasks.filter(task=>task.id!==id)}:current);
  return <View style={styles.aiArea}>{!expanded&&<><View style={[styles.stackSlip,styles.stackBack]}/><View style={[styles.stackSlip,styles.stackMiddle]}/></>}<Animated.View style={[styles.aiCard,{maxHeight:anim.interpolate({inputRange:[0,1],outputRange:[104,720]})}]}><Pressable accessibilityRole="button" accessibilityLabel={expanded?'Collapse AI subtask builder':'Expand AI subtask builder'} onPress={toggle}><View style={styles.aiHeader}><View style={styles.aiSpark}><Text>✦</Text></View><View style={{flex:1,marginLeft:11}}><Text style={styles.aiLabel}>AI SUBTASK BUILDER</Text><Text style={styles.aiTitle} numberOfLines={1}>{chore||'Describe a family task'}</Text></View><Text style={styles.expand}>{expanded?'−':'+'}</Text></View></Pressable>{expanded&&<View style={styles.subtaskList}><Text style={styles.aiQuestion}>What needs to get done?</Text><TextInput value={chore} onChangeText={value=>{setChore(value);setPlan(null);setError('')}} placeholder="Describe the main family task" placeholderTextColor={C.muted} maxLength={500} style={styles.aiPrompt}/>{plan?.tasks.map((x,i)=><View key={x.id} style={styles.subtaskRow}><View style={styles.subtaskNumber}><Text style={styles.subtaskNumberText}>{i+1}</Text></View><TextInput value={x.title} onChangeText={title=>updateTitle(x.id,title)} style={styles.subtaskInput}/><Pressable accessibilityRole="button" accessibilityLabel={`Remove ${x.title}`} onPress={()=>remove(x.id)} hitSlop={10}><Text style={styles.remove}>×</Text></Pressable></View>)}{!!error&&<Text style={styles.aiError}>{error}</Text>}<View style={styles.aiActions}>{plan&&<ScalePress onPress={generate} disabled={generating} style={styles.secondarySmall}><Text style={styles.secondaryText}>Regenerate</Text></ScalePress>}<ScalePress onPress={plan?()=>onPlanGenerated(chore,plan):generate} disabled={generating||(plan?plan.tasks.length===0:chore.trim().length<3)} style={styles.acceptSmall}>{generating?<ActivityIndicator size="small" color={C.white}/>:<Text style={styles.acceptText}>{plan?'Review plan':'Generate with AI'}</Text>}</ScalePress></View></View>}</Animated.View></View>;
}

export default function HomeScreen({userName='Noor',familyName='Noor Family',onNavigateToFood,onNavigateToTransport,onNavigateToPlanning,onNavigateToCleanliness,onNavigateToPlans,onPlanGenerated,onOpenTasks,onOpenProfile}:HomeScreenProps) {
  const screen=Dimensions.get('window'), roomHeight=Math.max(220,Math.min(screen.height*.34,310));
  const [section,setSection]=useState<CategoryKey|null>(null),[sheet,setSheet]=useState<SheetMode>(null),[radialOpen,setRadialOpen]=useState(false),[toast,setToast]=useState<string|null>(null),[connection,setConnection]=useState<ConnectionState>('empty'),[requestTitle,setRequestTitle]=useState('Pickup from training'),[requestTime,setRequestTime]=useState('4:15 PM');
  const radial=useRef(new Animated.Value(0)).current,fridge=useRef(new Animated.Value(0)).current,door=useRef(new Animated.Value(0)).current,table=useRef(new Animated.Value(0)).current,picture=useRef(new Animated.Value(0)).current,timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const layout=useMemo(()=>({fridge:{left:'2%' as const,bottom:4,width:screen.width*.27,height:roomHeight*.83},table:{left:'34%' as const,bottom:0,width:screen.width*.31,height:roomHeight*.44},picture:{left:'37%' as const,top:10,width:screen.width*.25,height:roomHeight*.31},door:{right:'2%' as const,bottom:3,width:screen.width*.27,height:roomHeight*.92}}),[screen.width,roomHeight]);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
  const flash=(m:string)=>{if(timer.current)clearTimeout(timer.current);setToast(m);timer.current=setTimeout(()=>setToast(null),1800)};
  const radialMenu=(open:boolean)=>{if(open)setRadialOpen(true);Animated.spring(radial,{toValue:open?1:0,useNativeDriver:true,speed:open?13:20,bounciness:open?6:0}).start(()=>{if(!open)setRadialOpen(false)})};
  const openObject=(key:CategoryKey,value:Animated.Value)=>Animated.sequence([Animated.spring(value,{toValue:1,useNativeDriver:true,speed:18}),Animated.delay(120)]).start(()=>navigate(key));
  const leave=()=>{setSection(null);[fridge,door,table,picture].forEach(v=>v.setValue(0))};
  const navigate=(key:CategoryKey)=>{
    const callback={food:onNavigateToFood,transport:onNavigateToTransport,planning:onNavigateToPlanning??onNavigateToPlans,cleanliness:onNavigateToCleanliness}[key];
    if(callback)callback();else setSection(key);
  };
  const ask=(_cat:CategoryKey,title:string,time:string,to:string)=>{setRequestTitle(title);setRequestTime(time);setSheet(null);setConnection('requestSent');flash(`Sent to ${to}`)};
  const offer=()=>{setSheet(null);setRequestTitle('Pickup from training');setRequestTime('4:15 PM');setConnection('offerReceived');flash('Omar received your offer')};
  if(section)return <SectionScreen item={category(section)} onBack={leave}/>;
  return <SafeAreaView style={styles.safe}><StatusBar barStyle="dark-content" backgroundColor={C.paper}/><View style={{flex:1}}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>{familyName.toUpperCase()} · DUBAI</Text><Text style={styles.hello}>Hey, {userName}</Text><Text style={styles.headerSub}>Your family space is awake.</Text></View><ScalePress onPress={()=>onOpenProfile?.()} label="Create or edit profile"><Avatar member={ME} size={50} badge={false}/></ScalePress></View>
    <View style={styles.familyStrip}>{FAMILY.map(m=><ScalePress key={m.id} onPress={()=>flash(`${m.name} · ${LOC[m.location].label}`)} style={styles.familyPerson}><Avatar member={m} size={45}/><Text style={styles.familyName}>{m.name}</Text></ScalePress>)}</View>
    <View style={styles.needsHead}><Text style={styles.sectionLabel}>ACTIVE AT HOME</Text><Text style={styles.mutedTiny}>3 needs</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.needsRail}>{NEEDS.map((n,i)=>{const cat=category(n.category);return <ScalePress key={n.id} onPress={()=>{setRequestTitle(n.title);setRequestTime(n.detail);onOpenTasks?onOpenTasks():flash(n.title)}} style={[styles.needSlip,{backgroundColor:cat.color,transform:[{rotate:i===1?'1deg':'-1deg'}]}]}><View style={styles.needTop}><Text style={styles.needMark}>{cat.mark}</Text><Text style={styles.needDetail}>{n.detail}</Text></View><Text style={styles.needTitle}>{n.title}</Text></ScalePress>})}</ScrollView>
    <View style={styles.askOffer}><View><Text style={styles.askKicker}>TOGETHER, SIMPLY</Text><Text style={styles.askTitle}>What do you need today?</Text></View><View style={styles.askButtons}><ScalePress onPress={()=>setSheet('ask')} style={[styles.askButton,{backgroundColor:C.yellow}]}><Text style={styles.askButtonText}>Ask</Text><Text style={styles.arrow}>↗</Text></ScalePress><ScalePress onPress={()=>setSheet('offer')} style={[styles.askButton,{backgroundColor:C.mint}]}><Text style={styles.askButtonText}>Offer</Text><Text style={styles.arrow}>↗</Text></ScalePress></View></View>
    <ConnectionPanel state={connection} title={requestTitle} time={requestTime} onMeet={()=>setConnection('connected')} onView={()=>navigate('transport')}/><AiStack onPlanGenerated={onPlanGenerated??((_chore,_plan)=>flash('Task plan is ready'))}/>
    <View style={styles.roomHead}><View><Text style={styles.sectionLabel}>OUR HOME</Text><Text style={styles.roomTitle}>Tap into family life</Text></View><Text style={styles.mutedTiny}>Four shared spaces</Text></View><View style={[styles.roomFrame,{height:roomHeight}]}><ImageBackground source={ASSETS.room} style={{flex:1}} resizeMode="cover"><HomeObject label="Food" image={ASSETS.fridge} tint={C.mint} onPress={()=>openObject('food',fridge)} style={layout.fridge}><Animated.Image source={ASSETS.fridge} style={[styles.objectImage,{opacity:fridge.interpolate({inputRange:[0,1],outputRange:[1,0]})}]} resizeMode="contain"/><Animated.Image source={ASSETS.fridgeOpen} style={[styles.objectImage,styles.absoluteImage,{opacity:fridge}]} resizeMode="contain"/></HomeObject><HomeObject label="Clean" image={ASSETS.table} tint={C.peach} onPress={()=>openObject('cleanliness',table)} style={layout.table}/><HomeObject label="Plan" image={ASSETS.picture} tint={C.lavender} onPress={()=>openObject('planning',picture)} style={layout.picture}/><HomeObject label="Go" image={ASSETS.door} tint={C.blue} onPress={()=>openObject('transport',door)} style={layout.door}/></ImageBackground></View><View style={{height:78}}/>
  </ScrollView>
  {radialOpen&&<View style={styles.radialLayer} pointerEvents="box-none"><Pressable style={StyleSheet.absoluteFill} onPress={()=>radialMenu(false)}><Animated.View style={[styles.radialDim,{opacity:radial}]}/></Pressable>{CATEGORIES.map((cat,i)=>{const delayed=radial.interpolate({inputRange:[i*.08,.55+i*.08,1],outputRange:[0,1,1],extrapolate:'clamp'});return <Animated.View key={cat.key} style={[styles.radialWrap,{opacity:delayed,transform:[{translateX:delayed.interpolate({inputRange:[0,1],outputRange:[0,cat.dx]})},{translateY:delayed.interpolate({inputRange:[0,1],outputRange:[0,cat.dy]})},{scale:delayed}]}]}><ScalePress onPress={()=>{radialMenu(false);setTimeout(()=>navigate(cat.key),180)}} style={{alignItems:'center'}}><View style={[styles.radialBubble,{backgroundColor:cat.color}]}><Image source={cat.image} style={styles.radialImage} resizeMode="contain"/></View><Text style={styles.radialLabel}>{cat.label}</Text></ScalePress></Animated.View>})}</View>}
  <Pressable accessibilityRole="button" accessibilityLabel={radialOpen?'Close category menu':'Open category menu'} onPress={()=>radialMenu(!radialOpen)} style={styles.fab}><Animated.Text style={[styles.fabText,{transform:[{rotate:radial.interpolate({inputRange:[0,1],outputRange:['0deg','45deg']})}]}]}>+</Animated.Text></Pressable>
  {toast&&<View style={styles.toast}><Text style={styles.toastText}>{toast}</Text></View>}{sheet&&<AskOfferSheet visible mode={sheet} onClose={()=>setSheet(null)} onAsk={ask} onOffer={offer}/>}</View></SafeAreaView>;
}

const styles=StyleSheet.create({
  safe:{flex:1,backgroundColor:C.paper,paddingTop:Platform.OS==='android'?StatusBar.currentHeight:0},scroll:{paddingBottom:18},disabled:{opacity:.45},eyebrow:{color:C.brand,fontSize:10,fontWeight:'800',letterSpacing:1.4},header:{paddingHorizontal:20,paddingTop:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},hello:{marginTop:2,color:C.ink,fontSize:31,lineHeight:35,fontWeight:'800',letterSpacing:-1},headerSub:{color:C.muted,fontSize:12.5,marginTop:2},
  avatarRing:{alignItems:'center',justifyContent:'center',backgroundColor:C.white,borderWidth:2.5},highlight:{shadowColor:C.blue,shadowOpacity:.95,shadowRadius:10,elevation:7},liveDot:{position:'absolute',top:1,left:3,width:10,height:10,borderRadius:5,borderWidth:2,borderColor:C.paper},skillBadge:{position:'absolute',left:-6,right:-6,bottom:-15,height:19,borderRadius:10,paddingHorizontal:5,backgroundColor:C.ink,flexDirection:'row',alignItems:'center',justifyContent:'center'},skillMark:{color:C.yellow,fontSize:9,marginRight:2},skillText:{color:C.white,fontSize:7.5,fontWeight:'800'},familyStrip:{marginTop:20,paddingHorizontal:18,flexDirection:'row',justifyContent:'space-around',columnGap:12},familyPerson:{minWidth:82,alignItems:'center',paddingHorizontal:5,paddingBottom:22},familyName:{marginTop:11,color:C.ink,fontSize:11,fontWeight:'700'},
  needsHead:{marginTop:15,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between'},sectionLabel:{color:C.brand,fontSize:10,fontWeight:'900',letterSpacing:1.3},mutedTiny:{color:C.muted,fontSize:10.5},needsRail:{paddingHorizontal:20,paddingVertical:11,gap:10},needSlip:{width:154,minHeight:84,borderRadius:16,padding:12,borderWidth:1,borderColor:'rgba(21,40,32,.1)',shadowColor:C.ink,shadowOpacity:.08,shadowRadius:6,elevation:2},needTop:{flexDirection:'row',justifyContent:'space-between'},needMark:{width:23,height:23,borderRadius:8,overflow:'hidden',textAlign:'center',paddingTop:4,backgroundColor:'rgba(255,255,255,.64)',color:C.ink,fontSize:10,fontWeight:'900'},needDetail:{color:C.muted,fontSize:9.5,fontWeight:'700'},needTitle:{color:C.ink,fontSize:13.5,lineHeight:17,fontWeight:'800',marginTop:9,maxWidth:128},
  askOffer:{marginHorizontal:20,marginTop:5,padding:17,borderRadius:24,backgroundColor:C.ink,flexDirection:'row',alignItems:'center',justifyContent:'space-between',shadowColor:C.ink,shadowOpacity:.17,shadowRadius:12,elevation:5},askKicker:{color:C.mint,fontSize:9,fontWeight:'900',letterSpacing:1.2},askTitle:{color:C.white,fontSize:17,lineHeight:21,fontWeight:'800',marginTop:4,maxWidth:155},askButtons:{flexDirection:'row',gap:7},askButton:{minWidth:66,height:47,paddingHorizontal:10,borderRadius:15,justifyContent:'center'},askButtonText:{color:C.ink,fontSize:13,fontWeight:'900'},arrow:{position:'absolute',right:7,top:5,color:C.ink,fontSize:10},
  waiting:{marginHorizontal:20,marginTop:13,height:43,paddingHorizontal:14,borderRadius:14,backgroundColor:C.blue,flexDirection:'row',alignItems:'center'},waitDot:{width:9,height:9,borderRadius:5,marginRight:9,backgroundColor:C.brand},waitText:{color:C.ink,fontSize:11.5,fontWeight:'700'},connection:{marginHorizontal:20,marginTop:13,borderRadius:22,padding:15,backgroundColor:C.white,borderWidth:1,borderColor:C.line},connectionHead:{flexDirection:'row',justifyContent:'space-between'},connectionKicker:{color:C.brand,fontSize:9,fontWeight:'900',letterSpacing:1.1},connectionTitle:{color:C.ink,fontSize:16,fontWeight:'800',marginTop:2},connectionTime:{color:C.muted,fontSize:10.5,fontWeight:'700'},trackRow:{height:62,marginTop:8,flexDirection:'row',alignItems:'center'},track:{flex:1,height:7,marginHorizontal:2,borderRadius:5,backgroundColor:'#DFE5E1',justifyContent:'center'},trackFill:{height:7,borderRadius:5,backgroundColor:C.orange},centre:{position:'absolute',alignSelf:'center',width:32,height:32,borderRadius:16,backgroundColor:C.ink,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:C.white},centreDone:{backgroundColor:C.orange},centreText:{color:C.white,fontSize:14,fontWeight:'900'},connectionNames:{marginTop:-7,paddingHorizontal:3,flexDirection:'row',justifyContent:'space-between'},tiny:{color:C.muted,fontSize:9,fontWeight:'700'},meetButton:{alignSelf:'center',marginTop:8,minWidth:150,height:40,borderRadius:13,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'},meetText:{color:C.white,fontSize:12.5,fontWeight:'900'},
  aiArea:{marginHorizontal:20,marginTop:14,paddingBottom:9},stackSlip:{position:'absolute',left:10,right:10,height:95,borderRadius:20,borderWidth:1,borderColor:C.line},stackBack:{top:10,backgroundColor:C.peach,transform:[{rotate:'-1.2deg'}]},stackMiddle:{top:5,backgroundColor:C.lavender,transform:[{rotate:'.9deg'}]},aiCard:{minHeight:104,overflow:'hidden',borderRadius:20,padding:15,backgroundColor:C.white,borderWidth:1,borderColor:C.line},aiHeader:{minHeight:70,flexDirection:'row',alignItems:'center'},aiSpark:{width:39,height:39,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:C.lavender},aiLabel:{color:C.brand,fontSize:8.5,fontWeight:'900',letterSpacing:1.1},aiTitle:{color:C.ink,fontSize:15,fontWeight:'800',marginTop:3},expand:{color:C.ink,fontSize:24},subtaskList:{borderTopWidth:1,borderTopColor:C.line,paddingTop:13},aiQuestion:{color:C.ink,fontSize:19,lineHeight:23,fontWeight:'900',letterSpacing:-.5,marginBottom:9},aiPrompt:{minHeight:50,borderRadius:14,paddingHorizontal:13,paddingVertical:10,marginBottom:7,backgroundColor:C.paper,color:C.ink,fontSize:13,fontWeight:'700',borderWidth:1,borderColor:C.line},subtaskRow:{minHeight:43,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.line},subtaskNumber:{width:24,height:24,borderRadius:8,backgroundColor:C.mint,alignItems:'center',justifyContent:'center'},subtaskNumberText:{color:C.brand,fontSize:9,fontWeight:'900'},subtaskInput:{flex:1,height:40,paddingHorizontal:9,color:C.ink,fontSize:12.5},remove:{color:C.muted,fontSize:20,paddingHorizontal:3},aiError:{color:'#AD3015',fontSize:10.5,lineHeight:15,fontWeight:'700',marginTop:7},aiActions:{flexDirection:'row',justifyContent:'flex-end',gap:8,marginTop:12},secondarySmall:{height:39,borderRadius:13,paddingHorizontal:13,justifyContent:'center',borderWidth:1,borderColor:C.line},secondaryText:{color:C.ink,fontSize:11,fontWeight:'800'},acceptSmall:{minWidth:122,height:39,borderRadius:13,paddingHorizontal:15,alignItems:'center',justifyContent:'center',backgroundColor:C.brand},acceptText:{color:C.white,fontSize:11,fontWeight:'800'},accepted:{height:39,marginTop:8,borderRadius:12,backgroundColor:C.mint,alignItems:'center',justifyContent:'center'},acceptedText:{color:C.ink,fontSize:11.5,fontWeight:'800'},
  roomHead:{marginTop:19,marginBottom:10,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},roomTitle:{color:C.ink,fontSize:19,fontWeight:'800',marginTop:2},roomFrame:{marginHorizontal:10,borderRadius:27,overflow:'hidden',borderWidth:1,borderColor:C.line,backgroundColor:'#E9E1D2'},homeObject:{position:'absolute',alignItems:'center'},objectFill:{flex:1,alignSelf:'stretch'},objectImage:{width:'100%',height:'100%'},absoluteImage:{position:'absolute',left:0,top:0},objectLabel:{position:'absolute',bottom:-1,paddingHorizontal:9,paddingVertical:4,borderRadius:9,borderWidth:1,borderColor:'rgba(21,40,32,.12)'},objectLabelText:{color:C.ink,fontSize:9.5,fontWeight:'900'},
  fab:{position:'absolute',right:20,bottom:20,zIndex:50,width:60,height:60,borderRadius:21,backgroundColor:C.brand,alignItems:'center',justifyContent:'center',shadowColor:C.brand,shadowOpacity:.38,shadowRadius:14,elevation:10},fabText:{color:C.white,fontSize:37,lineHeight:40,fontWeight:'300'},radialLayer:{...StyleSheet.absoluteFill,zIndex:40},radialDim:{flex:1,backgroundColor:C.scrim},radialWrap:{position:'absolute',right:25,bottom:27},radialBubble:{width:60,height:60,borderRadius:21,borderWidth:2,borderColor:C.white,alignItems:'center',justifyContent:'center',shadowColor:'#000',shadowOpacity:.24,shadowRadius:9,elevation:7},radialImage:{width:40,height:40},radialLabel:{marginTop:4,color:C.white,fontSize:10.5,fontWeight:'900'},toast:{position:'absolute',zIndex:80,bottom:92,alignSelf:'center',maxWidth:'82%',backgroundColor:C.ink,borderRadius:13,paddingHorizontal:17,paddingVertical:11},toastText:{color:C.white,fontSize:12.5,fontWeight:'700'},
  modalRoot:{flex:1,justifyContent:'flex-end'},modalScrim:{...StyleSheet.absoluteFill,backgroundColor:C.scrim},sheet:{maxHeight:'88%',paddingHorizontal:20,paddingTop:9,paddingBottom:Platform.OS==='ios'?28:20,borderTopLeftRadius:30,borderTopRightRadius:30,backgroundColor:C.paper},sheetHandle:{alignSelf:'center',width:42,height:4,borderRadius:3,backgroundColor:'rgba(21,40,32,.22)',marginBottom:15},sheetKicker:{color:C.brand,fontSize:9.5,fontWeight:'900',letterSpacing:1.4},sheetTitle:{color:C.ink,fontSize:27,lineHeight:33,fontWeight:'800',letterSpacing:-.6,marginTop:2,marginBottom:16},fieldLabel:{color:C.muted,fontSize:8.5,fontWeight:'900',letterSpacing:1.2,marginTop:11,marginBottom:7},categoryRow:{gap:8,paddingRight:10},categoryPill:{width:91,height:70,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},categoryPillImage:{width:37,height:37},categoryPillText:{color:C.ink,fontSize:9.5,fontWeight:'800',marginTop:2},input:{height:51,borderRadius:15,paddingHorizontal:14,backgroundColor:C.white,borderWidth:1,borderColor:C.line,color:C.ink,fontSize:14},choiceRow:{flexDirection:'row',gap:8},choice:{flex:1,height:40,paddingHorizontal:8,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:C.white,borderWidth:1,borderColor:C.line},choiceSelected:{backgroundColor:C.ink,borderColor:C.ink},choiceText:{color:C.ink,fontSize:10.5,fontWeight:'800'},choiceTextSelected:{color:C.white},primaryButton:{height:52,marginTop:21,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:C.brand},primaryText:{color:C.white,fontSize:14,fontWeight:'900'},
  sentState:{minHeight:280,alignItems:'center',justifyContent:'center'},sentMark:{width:64,height:64,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:C.mint},sentMarkText:{color:C.brand,fontSize:30,fontWeight:'900'},sentTitle:{color:C.ink,fontSize:24,fontWeight:'800',marginTop:17},sentSub:{maxWidth:255,color:C.muted,fontSize:12.5,lineHeight:18,textAlign:'center',marginTop:6},requestTicket:{minHeight:105,borderRadius:19,overflow:'hidden',flexDirection:'row',alignItems:'center',backgroundColor:C.white,borderWidth:1,borderColor:C.line,paddingRight:15},ticketStripe:{alignSelf:'stretch',width:7,marginRight:13,backgroundColor:C.blue},requestCopy:{flex:1},requestFrom:{color:'#397CB0',fontSize:8.5,fontWeight:'900',letterSpacing:1},requestTitle:{color:C.ink,fontSize:15,fontWeight:'800',marginTop:4},requestTime:{color:C.muted,fontSize:10.5,marginTop:5},matchNote:{marginTop:12,padding:13,borderRadius:15,flexDirection:'row',alignItems:'center',backgroundColor:C.lavender},matchMark:{width:28,color:C.ink,fontSize:19},matchText:{flex:1,color:C.ink,fontSize:11.5,lineHeight:16},matchStrong:{fontWeight:'900'},
  sectionScreen:{flex:1},sectionHeader:{paddingHorizontal:20,paddingTop:12,flexDirection:'row',alignItems:'center',gap:13},backButton:{width:43,height:43,borderRadius:14,backgroundColor:'rgba(255,255,255,.72)',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(21,40,32,.12)'},backGlyph:{color:C.ink,fontSize:29,lineHeight:31},sectionTitle:{color:C.ink,fontSize:29,lineHeight:34,fontWeight:'800'},sectionArtWrap:{height:'38%',minHeight:220,alignItems:'center',justifyContent:'center'},sectionHalo:{position:'absolute',width:230,height:230,borderRadius:115,backgroundColor:'rgba(255,255,255,.32)'},sectionArt:{width:'55%',height:'80%'},sectionContent:{flex:1,margin:14,padding:21,borderRadius:28,backgroundColor:C.paper},readyRow:{flexDirection:'row',alignItems:'center'},readyDot:{width:9,height:9,borderRadius:5,marginRight:8,backgroundColor:'#35A36F'},readyText:{color:C.brand,fontSize:10,fontWeight:'900'},sectionPrompt:{color:C.ink,fontSize:22,lineHeight:27,fontWeight:'800',maxWidth:290,marginTop:13},backendSlot:{flex:1,minHeight:150,marginTop:18,borderRadius:20,borderWidth:1.5,borderStyle:'dashed',borderColor:'rgba(21,40,32,.24)',alignItems:'center',justifyContent:'center',paddingHorizontal:27},backendLabel:{color:C.muted,fontSize:8.5,fontWeight:'900',letterSpacing:1.3},backendTitle:{color:C.ink,fontSize:14,lineHeight:20,fontWeight:'700',textAlign:'center',marginTop:7},
});
