import React, { useRef, useState } from 'react';
import { Animated, Modal, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../theme';

interface PlansScreenProps { onBack: () => void; }
type Sheet = 'new' | 'suggest' | 'help' | 'science' | 'meal' | null;

const dayPlans: Record<string, {title:string; place:string; tone:string}> = {
  Wed:{title:'Midweek reset',place:'Home · a quiet evening',tone:theme.colors.school}, Thu:{title:'Science fair prep',place:'Kitchen table · 6:00 PM',tone:theme.colors.school}, Fri:{title:'Friday by the water',place:'Creek Park · everyone’s invited',tone:theme.colors.transport}, Sat:{title:'Cook something new',place:'Home · 7:30 PM',tone:theme.colors.meals}, Sun:{title:'Family week ahead',place:'Home · 7:00 PM',tone:theme.colors.plans},
};

export const PlansScreen: React.FC<PlansScreenProps> = ({ onBack }) => {
  const [day,setDay] = useState('Fri'); const [accepted,setAccepted] = useState(false); const [sheet,setSheet] = useState<Sheet>(null);
  const scale = useRef(new Animated.Value(1)).current;
  const chooseDay=(x:string)=>{Animated.sequence([Animated.timing(scale,{toValue:.97,duration:90,useNativeDriver:true}),Animated.spring(scale,{toValue:1,useNativeDriver:true})]).start();setDay(x);setAccepted(false)};
  const plan=dayPlans[day];
  return <SafeAreaView style={styles.safe}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.header}><TouchableOpacity onPress={onBack} style={styles.back}><Ionicons name="chevron-back" size={22} color={theme.colors.textPrimary}/></TouchableOpacity><View style={{flex:1}}><Text style={styles.kicker}>TOGETHER NEXT</Text><Text style={styles.title}>Family plans</Text></View><TouchableOpacity style={styles.new} onPress={()=>setSheet('new')}><Ionicons name="add" size={25} color={theme.colors.plansDark}/></TouchableOpacity></View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days}>{['Wed','Thu','Fri','Sat','Sun'].map((x,i)=><TouchableOpacity key={x} onPress={()=>chooseDay(x)} style={[styles.day,day===x&&styles.dayActive]}><Text style={[styles.dayName,day===x&&styles.dayActiveText]}>{x}</Text><Text style={[styles.dayNum,day===x&&styles.dayActiveText]}>{9+i}</Text></TouchableOpacity>)}</ScrollView>
      <Animated.View style={[styles.feature,{transform:[{scale}]}]}>
        <View style={[styles.sky,{backgroundColor:plan.tone}]}><View style={styles.sun}/><View style={styles.cloud}/><View style={styles.water}/><View style={styles.land}/><View style={styles.pin}><Ionicons name="location" size={17} color={theme.colors.transportDark}/></View></View>
        <View style={styles.featureCopy}><View style={styles.featureTop}><Text style={styles.overline}>{day.toUpperCase()} · 4:00 PM</Text><View style={styles.agreed}><Ionicons name="people" size={14} color={theme.colors.plansDark}/><Text style={styles.agreedText}>{accepted?'Everyone is in':'3 of 4 are in'}</Text></View></View><Text style={styles.featureTitle}>{plan.title}</Text><Text style={styles.place}>{plan.place}</Text>
          <View style={styles.route}>{[['basket','Snacks'],['walk','Sunset'],['restaurant','Dinner']].map((x,i)=><React.Fragment key={x[1]}><View style={styles.stop}><View style={styles.stopIcon}><Ionicons name={x[0] as any} size={17} color={[theme.colors.mealsDark,theme.colors.transportDark,theme.colors.plansDark][i]}/></View><Text style={styles.stopText}>{x[1]}</Text></View>{i<2&&<View style={styles.line}><View style={styles.lineDot}/></View>}</React.Fragment>)}</View>
          <View style={styles.actions}><TouchableOpacity onPress={()=>setAccepted(true)} style={[styles.primary,accepted&&styles.success]}><Ionicons name={accepted?'checkmark':'heart-outline'} size={17} color="#FFF"/><Text style={styles.primaryText}>{accepted?'You’re in':'I’m in'}</Text></TouchableOpacity><TouchableOpacity onPress={()=>setSheet('suggest')} style={styles.secondary}><Ionicons name="shuffle" size={16} color={theme.colors.textPrimary}/><Text style={styles.secondaryText}>Suggest</Text></TouchableOpacity><TouchableOpacity onPress={()=>setSheet('help')} style={styles.iconAction}><Ionicons name="hand-left" size={18} color={theme.colors.textPrimary}/></TouchableOpacity></View>
        </View>
      </Animated.View>
      <View style={styles.sectionRow}><Text style={styles.section}>Coming up</Text><Text style={styles.count}>2 shared moments</Text></View>
      <TouchableOpacity style={[styles.smallCard,{backgroundColor:theme.colors.school}]} onPress={()=>setSheet('science')}><View style={styles.smallIcon}><Ionicons name="flask" size={21} color={theme.colors.schoolDark}/></View><View style={{flex:1}}><Text style={styles.smallOverline}>SCHOOL · THU 17</Text><Text style={styles.smallTitle}>Science fair finish line</Text><Text style={styles.smallSub}>Noor needs a second pair of eyes</Text></View><View style={styles.miniBadge}><Text style={styles.miniBadgeText}>HELP?</Text></View></TouchableOpacity>
      <TouchableOpacity style={[styles.smallCard,{backgroundColor:theme.colors.meals}]} onPress={()=>setSheet('meal')}><View style={styles.smallIcon}><Ionicons name="restaurant" size={21} color={theme.colors.mealsDark}/></View><View style={{flex:1}}><Text style={styles.smallOverline}>MEALS · SAT 19</Text><Text style={styles.smallTitle}>Cook something new</Text><Text style={styles.smallSub}>Three recipes waiting for your vote</Text></View><Ionicons name="arrow-forward" size={20} color={theme.colors.mealsDark}/></TouchableOpacity>
    </ScrollView>
    <Modal visible={sheet!==null} transparent animationType="slide" onRequestClose={()=>setSheet(null)}><TouchableOpacity style={styles.shade} activeOpacity={1} onPress={()=>setSheet(null)}><TouchableOpacity activeOpacity={1} style={styles.sheet}><View style={styles.handle}/><Text style={styles.sheetKicker}>{sheet==='new'?'NEW FAMILY PLAN':sheet==='suggest'?'SUGGEST A CHANGE':sheet==='help'?'PICK A ROLE':'SHARED MOMENT'}</Text><Text style={styles.sheetTitle}>{sheet==='new'?'What should we do together?':sheet==='suggest'?'Change one part':sheet==='help'?'How will you help?':sheet==='science'?'Science fair finish line':'Cook something new'}</Text>
      {(sheet==='new'||sheet==='suggest')&&<View style={styles.options}>{['Time','Place','Activity'].map((x,i)=><TouchableOpacity key={x} style={[styles.option,{backgroundColor:[theme.colors.transport,theme.colors.plans,theme.colors.meals][i]}]}><Ionicons name={(['time','location','sparkles'] as const)[i]} size={20} color={theme.colors.textPrimary}/><Text style={styles.optionText}>{x}</Text></TouchableOpacity>)}</View>}
      {sheet==='help'&&<View style={styles.options}>{['Drive','Snacks','Photos'].map((x,i)=><TouchableOpacity key={x} style={[styles.option,{backgroundColor:[theme.colors.transport,theme.colors.meals,theme.colors.school][i]}]}><Ionicons name={(['car-sport','basket','camera'] as const)[i]} size={20} color={theme.colors.textPrimary}/><Text style={styles.optionText}>{x}</Text></TouchableOpacity>)}</View>}
      {(sheet==='science'||sheet==='meal')&&<View style={styles.detailBox}><Text style={styles.detailText}>{sheet==='science'?'Noor wants someone to review the display board—not do the project for her.':'Vote on one recipe, then split shopping and cooking between the family.'}</Text></View>}
      <TouchableOpacity style={styles.sheetButton} onPress={()=>setSheet(null)}><Text style={styles.sheetButtonText}>{sheet==='new'?'Create draft':'Done'}</Text><Ionicons name="arrow-forward" size={18} color="#FFF"/></TouchableOpacity>
    </TouchableOpacity></TouchableOpacity></Modal>
  </SafeAreaView>;
};

const styles=StyleSheet.create({
  safe:{flex:1,backgroundColor:theme.colors.background},content:{padding:18,paddingBottom:44,maxWidth:520,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:14},back:{width:42,height:42,borderRadius:15,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:theme.colors.border},new:{width:42,height:42,borderRadius:15,backgroundColor:theme.colors.plans,alignItems:'center',justifyContent:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:theme.colors.textMuted},title:{fontSize:28,fontWeight:'900',letterSpacing:-1,color:theme.colors.textPrimary},days:{gap:7,paddingBottom:18},day:{width:58,height:65,borderRadius:19,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:theme.colors.border},dayActive:{backgroundColor:theme.colors.textPrimary},dayName:{fontSize:10,fontWeight:'700',color:theme.colors.textMuted},dayNum:{fontSize:18,fontWeight:'900',color:theme.colors.textPrimary,marginTop:2},dayActiveText:{color:'#FFF'},
  feature:{borderRadius:30,overflow:'hidden',backgroundColor:'#FFF',borderWidth:1,borderColor:theme.colors.border,...theme.shadows.soft},sky:{height:145,overflow:'hidden'},sun:{position:'absolute',width:70,height:70,borderRadius:35,backgroundColor:theme.colors.connection,right:30,top:20},cloud:{position:'absolute',width:90,height:27,borderRadius:20,backgroundColor:'rgba(255,255,255,.75)',left:27,top:32},water:{position:'absolute',height:62,left:0,right:0,bottom:0,backgroundColor:'rgba(96,185,229,.48)'},land:{position:'absolute',width:260,height:90,borderRadius:100,backgroundColor:theme.colors.plans,bottom:-54,left:-30,transform:[{rotate:'-5deg'}]},pin:{position:'absolute',right:18,bottom:16,width:38,height:38,borderRadius:15,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center'},featureCopy:{padding:18},featureTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},overline:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:theme.colors.plansDark},agreed:{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:theme.colors.plans,paddingHorizontal:9,paddingVertical:6,borderRadius:14},agreedText:{fontSize:10,fontWeight:'800',color:theme.colors.plansDark},featureTitle:{fontSize:24,fontWeight:'900',letterSpacing:-.7,color:theme.colors.textPrimary,marginTop:7},place:{fontSize:12,color:theme.colors.textSecondary,marginTop:2},route:{flexDirection:'row',alignItems:'flex-start',marginVertical:22},stop:{alignItems:'center'},stopIcon:{width:42,height:42,borderRadius:14,backgroundColor:theme.colors.surfaceAlt,alignItems:'center',justifyContent:'center'},stopText:{fontSize:10,fontWeight:'700',color:theme.colors.textSecondary,marginTop:5},line:{flex:1,height:2,backgroundColor:theme.colors.border,marginTop:20,justifyContent:'center'},lineDot:{width:6,height:6,borderRadius:3,backgroundColor:theme.colors.connection,alignSelf:'center'},actions:{flexDirection:'row',gap:7},primary:{flex:1,minHeight:46,borderRadius:18,backgroundColor:theme.colors.textPrimary,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center'},success:{backgroundColor:theme.colors.plansDark},primaryText:{color:'#FFF',fontWeight:'800'},secondary:{minWidth:104,minHeight:46,borderRadius:18,backgroundColor:theme.colors.surfaceAlt,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:12,fontWeight:'800',color:theme.colors.textPrimary},iconAction:{width:46,height:46,borderRadius:18,backgroundColor:theme.colors.connection,alignItems:'center',justifyContent:'center'},
  sectionRow:{flexDirection:'row',alignItems:'baseline',justifyContent:'space-between',marginTop:24,marginBottom:10},section:{fontSize:18,fontWeight:'900',color:theme.colors.textPrimary},count:{fontSize:10,color:theme.colors.textMuted},smallCard:{minHeight:106,borderRadius:24,padding:15,marginBottom:10,flexDirection:'row',alignItems:'center',gap:11},smallIcon:{width:48,height:48,borderRadius:16,backgroundColor:'rgba(255,255,255,.65)',alignItems:'center',justifyContent:'center'},smallOverline:{fontSize:8,fontWeight:'900',letterSpacing:1,color:theme.colors.textSecondary},smallTitle:{fontSize:15,fontWeight:'900',color:theme.colors.textPrimary,marginTop:3},smallSub:{fontSize:11,color:theme.colors.textSecondary,marginTop:3},miniBadge:{backgroundColor:'rgba(255,255,255,.7)',paddingHorizontal:8,paddingVertical:6,borderRadius:11},miniBadgeText:{fontSize:8,fontWeight:'900',color:theme.colors.schoolDark},
  shade:{flex:1,backgroundColor:'rgba(30,32,43,.38)',justifyContent:'flex-end'},sheet:{backgroundColor:'#FFF',borderTopLeftRadius:32,borderTopRightRadius:32,padding:24,paddingBottom:36},handle:{width:42,height:5,borderRadius:3,backgroundColor:theme.colors.border,alignSelf:'center',marginBottom:18},sheetKicker:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:theme.colors.textMuted},sheetTitle:{fontSize:25,fontWeight:'900',letterSpacing:-.8,color:theme.colors.textPrimary,marginTop:3},options:{flexDirection:'row',gap:8,marginTop:20},option:{flex:1,height:92,borderRadius:21,alignItems:'center',justifyContent:'center',gap:8},optionText:{fontSize:11,fontWeight:'900',color:theme.colors.textPrimary},detailBox:{backgroundColor:theme.colors.surfaceAlt,borderRadius:22,padding:18,marginTop:20},detailText:{fontSize:14,lineHeight:21,color:theme.colors.textSecondary},sheetButton:{height:52,borderRadius:18,backgroundColor:theme.colors.textPrimary,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:22},sheetButtonText:{color:'#FFF',fontWeight:'900'},
});
