import React, { useState } from 'react';
import { Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Action, Avatar, HQ, Notice, PEOPLE, Screen, Tap } from './HomeQuestUI';

const PICTURE=require('./picture.png');
type PlanState='proposed'|'confirmed';
interface Stop{id:number;time:string;title:string;detail:string}
export interface PlanningScreenProps{onBack:()=>void}
const MOCK_STOPS:Stop[]=[{id:1,time:'9:00',title:'Leave home',detail:'Water and hats ready'},{id:2,time:'10:00',title:'Al Qudra cycle track',detail:'Easy family loop'},{id:3,time:'12:30',title:'Lakeside picnic',detail:'Shared lunch'}];

export default function PlanningScreen({onBack}:PlanningScreenProps){
 const [state,setState]=useState<PlanState>('proposed'),[votes,setVotes]=useState(['Omar','Ayesha']),[stops,setStops]=useState(MOCK_STOPS),[expanded,setExpanded]=useState(false),[approved,setApproved]=useState(false),[createOpen,setCreateOpen]=useState(false),[idea,setIdea]=useState('Friday beach evening'),[message,setMessage]=useState<string|null>(null);
 const flash=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(null),1600)};
 const join=()=>{if(!votes.includes('Noor'))setVotes(x=>[...x,'Noor']);setState('confirmed');flash("You're in — plan confirmed")};
 const generate=()=>{setStops([{id:11,time:'4:30',title:'Meet at home',detail:'Pack a light picnic'},{id:12,time:'5:15',title:'Kite Beach walk',detail:'Sunset route'},{id:13,time:'7:00',title:'Dinner nearby',detail:'Family chooses together'}]);setApproved(false);setExpanded(true);flash('New itinerary suggested')};
 return <Screen title="Plans & company" kicker="TIME TOGETHER" color={HQ.lavender} art={PICTURE} onBack={onBack}>
  <View style={s.destination}><Image source={PICTURE} style={s.picture} resizeMode="contain"/><View style={s.destCopy}><View style={[s.status,{backgroundColor:state==='confirmed'?HQ.mint:HQ.yellow}]}><Text style={s.statusText}>{state==='confirmed'?'CONFIRMED':'PROPOSED'}</Text></View><Text style={s.destTitle}>Al Qudra family morning</Text><Text style={s.destSub}>Friday · Outdoors · Dubai</Text></View></View>
  {message&&<Notice text={message}/>}<View style={s.actions}><Action text={votes.includes('Noor')?'I’m in ✓':"I'm in"} onPress={join}/><Action text="Suggest change" secondary onPress={()=>{setIdea('Later start at 10:00 AM');setCreateOpen(true)}}/></View>
  <View style={s.familyHead}><Text style={s.sectionTitle}>Family availability</Text><Text style={s.small}>{votes.length}/4 agreed</Text></View><View style={s.people}><Avatar source={PEOPLE.omar} name="Omar" badge="In" highlight/><Avatar source={PEOPLE.ayesha} name="Ayesha" badge="In" highlight/><Avatar source={PEOPLE.ali} name="Ali" badge="After 11"/><Avatar source={PEOPLE.noor} name="Noor" badge={votes.includes('Noor')?'In':'Open'} highlight={votes.includes('Noor')}/></View>
  <View style={s.itinerary}><Pressable onPress={()=>setExpanded(x=>!x)} style={s.itineraryHead}><View><Text style={s.aiLabel}>✦ AI ITINERARY · NEEDS APPROVAL</Text><Text style={s.itineraryTitle}>Shared route · {stops.length} stops</Text></View><Text style={s.plus}>{expanded?'−':'+'}</Text></Pressable>{expanded&&<View>{stops.map((x,i)=><Tap key={x.id} onPress={()=>flash(`${x.title} selected`)} style={s.stop}><View style={s.timeBox}><Text style={s.stopTime}>{x.time}</Text></View><View style={{flex:1}}><Text style={s.stopTitle}>{x.title}</Text><Text style={s.stopDetail}>{x.detail}</Text></View><Text style={s.stopArrow}>›</Text></Tap>)}{approved?<Notice text="Itinerary approved for the shared plan"/>:<View style={s.actions}><Action text="Generate again" secondary onPress={generate}/><Action text="Approve itinerary" onPress={()=>setApproved(true)}/></View>}</View>}</View>
  <View style={s.help}><View><Text style={s.helpLabel}>A SMALL WAY TO HELP</Text><Text style={s.helpTitle}>Picnic setup needs a hand</Text></View><Action text="Offer help" onPress={()=>flash('Help offered — no assignment made')}/></View>
  <Action text="Create plan" onPress={()=>setCreateOpen(true)}/>
  <Modal transparent visible={createOpen} animationType="slide" onRequestClose={()=>setCreateOpen(false)}><View style={s.modal}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setCreateOpen(false)}/><View style={s.sheet}><Text style={s.sheetTitle}>{idea.startsWith('Later')?'Suggest change':'Create a family plan'}</Text><TextInput value={idea} onChangeText={setIdea} style={s.input}/><View style={s.actions}><Action text="Cancel" secondary onPress={()=>setCreateOpen(false)}/><Action text="Share proposal" onPress={()=>{setCreateOpen(false);setState('proposed');flash('Proposal shared for family approval')}}/></View></View></View></Modal>
 </Screen>;
}
const s=StyleSheet.create({destination:{height:146,borderRadius:23,overflow:'hidden',backgroundColor:'#E6DDF0',flexDirection:'row',alignItems:'center',padding:13},picture:{width:118,height:125},destCopy:{flex:1},status:{alignSelf:'flex-start',borderRadius:8,paddingHorizontal:8,paddingVertical:4},statusText:{fontSize:8,fontWeight:'900',letterSpacing:1,color:HQ.ink},destTitle:{fontSize:20,lineHeight:24,fontWeight:'800',color:HQ.ink,marginTop:8},destSub:{fontSize:10.5,color:HQ.muted,marginTop:5},actions:{flexDirection:'row',gap:8,justifyContent:'flex-end',marginVertical:11},familyHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8},sectionTitle:{fontSize:18,fontWeight:'800',color:HQ.ink},small:{fontSize:10,color:HQ.muted},people:{flexDirection:'row',justifyContent:'space-between',marginVertical:13},itinerary:{borderRadius:20,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,padding:14,marginVertical:10},itineraryHead:{height:57,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},aiLabel:{fontSize:8.5,fontWeight:'900',letterSpacing:1,color:'#79538B'},itineraryTitle:{fontSize:15,fontWeight:'800',color:HQ.ink,marginTop:4},plus:{fontSize:24,color:HQ.ink},stop:{minHeight:59,borderTopWidth:1,borderTopColor:HQ.line,flexDirection:'row',alignItems:'center',gap:10},timeBox:{width:42,height:31,borderRadius:10,backgroundColor:HQ.lavender,alignItems:'center',justifyContent:'center'},stopTime:{fontSize:10,fontWeight:'900',color:HQ.ink},stopTitle:{fontSize:12.5,fontWeight:'800',color:HQ.ink},stopDetail:{fontSize:9.5,color:HQ.muted,marginTop:2},stopArrow:{fontSize:22,color:HQ.muted},help:{minHeight:82,borderRadius:18,backgroundColor:HQ.peach,padding:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:9},helpLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:HQ.brand},helpTitle:{fontSize:13,fontWeight:'800',color:HQ.ink,marginTop:5},modal:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(21,40,32,.5)'},sheet:{padding:22,paddingBottom:30,borderTopLeftRadius:28,borderTopRightRadius:28,backgroundColor:HQ.paper},sheetTitle:{fontSize:24,fontWeight:'800',color:HQ.ink,marginBottom:14},input:{height:49,borderRadius:14,paddingHorizontal:13,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,color:HQ.ink}});
