import React, { useEffect, useRef, useState } from 'react';
import { Animated, Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Action, Avatar, HQ, Notice, PEOPLE, Pill, Screen } from './HomeQuestUI';

const DOOR=require('./door.png');
type RideState='empty'|'pending'|'offered'|'confirmed';
export interface TransportScreenProps{onBack:()=>void}
const MOCK_DRIVERS=[{id:'omar',name:'Omar',source:PEOPLE.omar,badge:'→ Driver',available:true},{id:'ali',name:'Ali',source:PEOPLE.ali,badge:'⌁ Navigator',available:false}];

export default function TransportScreen({onBack}:TransportScreenProps){
 const [state,setState]=useState<RideState>('pending'),[askOpen,setAskOpen]=useState(false),[place,setPlace]=useState('Campus Gate 2'),[time,setTime]=useState('4:15 PM'),[message,setMessage]=useState<string|null>(null); const progress=useRef(new Animated.Value(0)).current,meet=useRef(new Animated.Value(0)).current;
 useEffect(()=>{if(state==='confirmed')Animated.parallel([Animated.timing(progress,{toValue:1,duration:650,useNativeDriver:false}),Animated.spring(meet,{toValue:1,useNativeDriver:true,speed:12})]).start()},[state,progress,meet]);
 const flash=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(null),1600)};
 const request=()=>{setAskOpen(false);setState('pending');flash('Pickup request sent')};
 const offer=()=>{setState('offered');flash('Omar offered a ride')};
 return <Screen title="Transport" kicker="FAMILY ON THE MOVE" color={HQ.blue} art={DOOR} onBack={onBack}>
  <View style={s.routeHero}><View style={s.routeLabel}><Text style={s.eyebrow}>{state==='confirmed'?'PICKUP CONFIRMED':state==='offered'?'OFFER RECEIVED':'PICKUP REQUEST'}</Text><Text style={s.place}>{place}</Text><Text style={s.when}>Today · {time}</Text></View><Image source={DOOR} style={s.door} resizeMode="contain"/></View>
  <View style={s.route}><Animated.View style={{transform:[{translateX:meet.interpolate({inputRange:[0,1],outputRange:[0,55]})}]}}><Avatar source={PEOPLE.noor} name="Noor" badge="Requesting"/></Animated.View><View style={s.road}><Animated.View style={[s.roadFill,{width:progress.interpolate({inputRange:[0,1],outputRange:['0%','100%']})}]}/><View style={[s.routeMark,state==='confirmed'&&s.routeMarkDone]}><Text style={s.routeMarkText}>{state==='confirmed'?'♥':'↔'}</Text></View></View><Animated.View style={{transform:[{translateX:meet.interpolate({inputRange:[0,1],outputRange:[0,-55]})}]}}><Avatar source={PEOPLE.omar} name="Omar" badge="→ Driver" highlight={state!=='pending'}/></Animated.View></View>
  {message&&<Notice text={message}/>}<View style={s.stateActions}>{state==='pending'&&<><Action text="Omar: Offer a ride" onPress={offer}/><Action text="Edit request" secondary onPress={()=>setAskOpen(true)}/></>}{state==='offered'&&<><Action text="Meet halfway" onPress={()=>setState('confirmed')}/><Action text="Not now" secondary onPress={()=>{setState('pending');flash('Offer left open')}}/></>}{state==='confirmed'&&<><Notice text={`Pickup confirmed · ${time}`}/><Action text="Mark picked up" secondary onPress={()=>{setState('empty');flash('Arrived safely')}}/></>}{state==='empty'&&<Action text="Ask for pickup" onPress={()=>setAskOpen(true)}/>}</View>
  <View style={s.sectionHead}><Text style={s.sectionTitle}>Available family</Text><Text style={s.small}>No live GPS used</Text></View><View style={s.drivers}>{MOCK_DRIVERS.map(d=><Pressable key={d.id} onPress={()=>flash(d.available?`${d.name} is available`:`${d.name} is busy right now`)} style={[s.driver,d.available&&s.driverAvailable]}><Avatar source={d.source} name={d.name} badge={d.badge} highlight={d.available}/><View style={{flex:1}}><Text style={s.driverStatus}>{d.available?'AVAILABLE NOW':'AVAILABLE AFTER 6'}</Text><Text style={s.driverText}>{d.available?'Soft match for this request':'Can help with route planning'}</Text></View></Pressable>)}</View>
  <View style={s.mapSlot}><Text style={s.mapKicker}>ROUTE PREVIEW</Text><View style={s.mapPath}><View style={s.mapDot}/><View style={s.mapLine}/><View style={[s.mapDot,{backgroundColor:HQ.orange}]}/></View><Text style={s.mapText}>{place} → Home</Text><Text style={s.mapHint}>Ready for the existing maps service</Text></View>
  <View style={s.bottomActions}><Action text="Ask for pickup" onPress={()=>setAskOpen(true)}/><Action text="Offer a ride" secondary onPress={()=>{setState('offered');flash('Ride offer shared')}}/></View>
  <Modal visible={askOpen} transparent animationType="slide" onRequestClose={()=>setAskOpen(false)}><View style={s.modal}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setAskOpen(false)}/><View style={s.sheet}><Text style={s.sheetTitle}>Ask for pickup</Text><Text style={s.field}>LOCATION</Text><TextInput value={place} onChangeText={setPlace} style={s.input}/><Text style={s.field}>TIME</Text><View style={s.times}>{['4:15 PM','5:00 PM','6:30 PM'].map(x=><Pill key={x} text={x} active={time===x} onPress={()=>setTime(x)}/>)}</View><Action text="Send request" onPress={request}/></View></View></Modal>
 </Screen>;
}
const s=StyleSheet.create({routeHero:{height:126,borderRadius:22,backgroundColor:'#D7E4EB',padding:16,flexDirection:'row',overflow:'hidden'},routeLabel:{flex:1,justifyContent:'center'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:'#397CB0'},place:{fontSize:21,fontWeight:'800',color:HQ.ink,marginTop:5},when:{fontSize:11,color:HQ.muted,marginTop:5},door:{width:92,height:120},route:{height:96,flexDirection:'row',alignItems:'center'},road:{flex:1,height:8,borderRadius:5,backgroundColor:'#D9E2E5',justifyContent:'center'},roadFill:{height:8,borderRadius:5,backgroundColor:HQ.orange},routeMark:{position:'absolute',alignSelf:'center',width:32,height:32,borderRadius:16,backgroundColor:HQ.ink,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:HQ.paper},routeMarkDone:{backgroundColor:HQ.orange},routeMarkText:{color:HQ.white,fontWeight:'900'},stateActions:{gap:8},sectionHead:{marginTop:19,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionTitle:{fontSize:18,fontWeight:'800',color:HQ.ink},small:{fontSize:9.5,color:HQ.muted},drivers:{gap:8,marginTop:10},driver:{minHeight:88,padding:10,borderRadius:18,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'#E7EAE5',borderWidth:1,borderColor:HQ.line},driverAvailable:{backgroundColor:HQ.white,borderColor:HQ.orange},driverStatus:{fontSize:8.5,fontWeight:'900',letterSpacing:1,color:HQ.brand},driverText:{fontSize:11,color:HQ.muted,marginTop:5},mapSlot:{marginTop:16,minHeight:108,borderRadius:18,padding:14,backgroundColor:HQ.white,borderWidth:1,borderStyle:'dashed',borderColor:HQ.line},mapKicker:{fontSize:8.5,fontWeight:'900',letterSpacing:1,color:HQ.brand},mapPath:{marginTop:13,flexDirection:'row',alignItems:'center'},mapDot:{width:13,height:13,borderRadius:7,backgroundColor:HQ.brand},mapLine:{flex:1,height:4,backgroundColor:HQ.blue},mapText:{fontSize:12,fontWeight:'800',color:HQ.ink,marginTop:8},mapHint:{fontSize:9.5,color:HQ.muted,marginTop:2},bottomActions:{marginTop:14,flexDirection:'row',gap:8},modal:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(21,40,32,.5)'},sheet:{padding:22,paddingBottom:30,borderTopLeftRadius:28,borderTopRightRadius:28,backgroundColor:HQ.paper,gap:10},sheetTitle:{fontSize:25,fontWeight:'800',color:HQ.ink},field:{fontSize:8.5,fontWeight:'900',letterSpacing:1,color:HQ.muted,marginTop:5},input:{height:48,borderRadius:14,paddingHorizontal:13,backgroundColor:HQ.white,borderWidth:1,borderColor:HQ.line,color:HQ.ink},times:{flexDirection:'row',gap:8,marginBottom:8}});
